version: '3'

vars:
  API: http://127.0.0.1:9001

dotenv:
  - .env

env:
  PUBLIC_LANDSCAPE: lapras

tasks:
  setup:
    desc: Setups
    cmds:
      - bun i

  dev:
    desc: Start development
    cmds:
      - bun run start

  build:
    desc: Build project
    cmds:
      - bun run build
