version: '3'

tasks:
  setup:
    desc: Setups
    cmds:
      - bun i

  dev:
    desc: Start development
    cmds:
      - bun run dev

  build:
    desc: Build project
    cmds:
      - bun run build
